version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - my_network
    depends_on:
      - db
    environment:
      - DATABASE_URI=mongodb://db:27017/mydatabase

  db:
    image: mongo
    networks:
      - my_network
    volumes:
      - ./data:/data/db

networks:
  my_network:

