version: '3.8'

services:
  app:
    build: .
    ports:
      - "5002:5002"
    volumes:
      - ./benefits.txt:/app/benefits.txt:ro
    depends_on:
      - db
    environment:
      DATABASE_URI: mongodb://db:27017/mydatabase

  db:
    image: mongo
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:

